Copied contract filter customize from 12.0 to 14.0 except i18n folder
SDIsl/sdi-addons pull request #130
Opened 2022-02-03 12:52 UTC by miguelLucendo

Basicamente lo que pone en el commit, he copiado de la rama 12 lo que me has dicho y he cambiado en el manifest la version y el author, lo unico que no he copiado ha sido i18n porque no lo he entendido bien y habia fechas de 2020

2022-02-03 12:57 UTC, JorgeQuinteros requested changes

2022-02-03 12:57 UTC, JorgeQuinteros commented on contract_filter_customize/__manifest__.py
> +    'author': 'Miguel Lucendo Esteban, SDi Soluciones Informáticas',
Cuando migramos un módulo debemos mantener la autoría de quienes lo crearon en su momento. Así que no quites mi nombre :)

2022-02-03 12:57 UTC, JorgeQuinteros commented
Agrega las traducciones para este módulo.

2022-02-03 13:00 UTC, miguelLucendo commented on contract_filter_customize/__manifest__.py
> +    'author': 'Miguel Lucendo Esteban, SDi Soluciones Informáticas',
Vale, perfecto, no lo sabia jajajaj, te vuelvo a poner, no te queria robar la autoria ;)
Lo de las traducciones después de comer me pongo con ello.

2022-02-03 14:45 UTC, JorgeQuinteros requested changes

2022-02-03 14:45 UTC, JorgeQuinteros commented on contract_filter_customize/__manifest__.py
> +    'author': 'Jorge Luis Quinteros, SDi Soluciones Informáticas',
Pero no quites el tuyo, que lo estás migrando tú, tienes que aparecer.
Por normal general el nombre de la empresa va último, así que pon tu nombre antes o después del mio, me es indiferente.

2022-02-09 11:54 UTC, JorgeQuinteros commented
Buenas @miguelLucendo  Cuando puedas revisa el comentario anterior.

2022-02-09 12:51 UTC, JorgeQuinteros requested changes

2022-02-09 12:51 UTC, JorgeQuinteros commented on contract_filter_customize/__manifest__.py
> +    'author': 'Jorge Luis Quinteros, Miguel Lucendo Esteban, \
No está mal, pero mejor utiliza las triples comillas simples cuando haya mucho texto
    'author': '''Jorge Luis Quinteros, Miguel Lucendo Esteban,
 SDi Soluciones Informáticas '''

2022-02-09 16:35 UTC, JorgeQuinteros approved these changes
LGTM!

2022-02-09 16:35 UTC, merged