[ADD] Added antiquity and actual_calendar fields based on calendar_ids of hr_employee
SDIsl/sdi-addons pull request #153
Opened 2022-05-03 15:12 UTC by miguelLucendo

2022-06-08 10:55 UTC, JorgeQuinteros requested changes

2022-06-08 10:55 UTC, JorgeQuinteros commented on hr_employee_calendar_planning_customize/models/hr_employee.py
> +            if years == 0 and days == 0:
Podrías probar con :
`if not years and not days:`
Creo que sería lo mismo porque 0 entería que es False. pruebalo y me dices

2022-06-08 10:55 UTC, JorgeQuinteros commented on hr_employee_calendar_planning_customize/models/hr_employee.py
> +        string='Years test',
Se te ha colado el "test"

2022-06-08 11:13 UTC, miguelLucendo commented
Ahora probando después de hacer el commit he visto que al agrupar por años, el orden que utiliza detecta que por ejemplo 58 años tiene que ir antes que 6 porque al ser un string entiendo que ordena alfabéticamente y el 5 va antes que el 6.

Como se podría arreglar eso? O lo dejamos así?

2022-06-16 16:26 UTC, JorgeQuinteros approved these changes

2022-06-16 16:26 UTC, merged