[ADD] Added field/s related to origin document on account.invoice based on contract or sale order
SDIsl/sdi-addons pull request #154
Opened 2022-05-03 15:19 UTC by miguelLucendo

2022-05-03 15:29 UTC, JorgeQuinteros requested changes

2022-05-03 15:29 UTC, JorgeQuinteros commented on account_invoice_origin_link/views/account_invoice_views.xml
> +            <xpath expr="//page[@name='other_info']//field[@name='origin']" position="after">
Hay más campos llamados "origin" en la vista, si no es así, con lo siguiente te valdría:
```
<field name="origin" position="after">
    <field name="related_sale_id" attrs="{'invisible': [('related_sale_id', '=', False)]}"/>
    <field name="related_contract_id" attrs="{'invisible': [('related_contract_id', '=', False)]}"/>
 </field>
```

2022-05-03 15:29 UTC, JorgeQuinteros commented on account_invoice_origin_link/models/account_invoice.py
> +
Espacio en blanco fuera.
```suggestion
```

2022-05-03 15:39 UTC, miguelLucendo commented on account_invoice_origin_link/views/account_invoice_views.xml
> +            <xpath expr="//page[@name='other_info']//field[@name='origin']" position="after">
Si, estuve peleándome un buen rato porque si lo ponía como has dicho tú, me petaba diciendo que el campo que creaba yo no existía pero si lo ponía en otro sitio si. Hay un origin con el atributo invisible en otra parte de la vista.

2022-05-03 15:40 UTC, miguelLucendo commented on account_invoice_origin_link/models/account_invoice.py
> +
Te refieres a que no haya salto de línea entre los dos campos creados, no?

2022-05-06 12:31 UTC, JorgeQuinteros approved these changes
LGTM!

2022-05-06 12:31 UTC, merged