[IMP]: New users group that can archive contact records
SDIsl/sdi-addons pull request #156
Opened 2022-05-04 10:26 UTC by Jeggrerd

For contact records, archive smartbutton will be hide to anyone who is not in the Archive Manager group.

2022-05-06 12:55 UTC, JorgeQuinteros requested changes

2022-05-06 12:55 UTC, JorgeQuinteros commented on hide_archive_button_by_group/security/archive_security.xml
> +        <field name="name">Archive Manager</field>
Creo que sería más claro un: "Archivar Contactos"
Porque especificamos la funcionalidad del grupo, ya que sólo aplica a Contactos.

Además yo lo agregaría al siguiente grupo:

            <field name="category_id" ref="base.module_category_extra"/>

2022-05-06 12:55 UTC, JorgeQuinteros commented on hide_archive_button_by_group/__manifest__.py
> +     'security/archive_security.xml',
El nombre del fichero, para que sea más reconocible pondría `res_partner_security.xml`.
Y en este módulo añadiríamos varios grupos para diferentes modelos, entonces le pondría `security.xml`

2022-05-06 12:55 UTC, JorgeQuinteros commented on hide_archive_button_by_group/__manifest__.py
> +    'depends': ['base', ],
```suggestion
    'depends': ['base'],
```
Como es módulo es muy concreto lo puedes hacer como te comento, ya que no agregaremos más módulos depends.
Lo siguiente también me hubiera valido:
    'depends': [
           'base',
     ],

2022-05-09 14:40 UTC, JorgeQuinteros requested changes

2022-05-09 14:40 UTC, JorgeQuinteros commented on hide_archive_button_by_group_for_contacts/__manifest__.py
> +    'name': 'Hide Archive Button By Groups For Contacts',
Un último comentario,
intentamos que el nombre del módulo empiece con el nombre del modelo al que afecta, un ejemplo para este módulo sería.
`partner_hide_archive_button`
Por ejemplo si en el futuro haces un módulo parecido que afecta a los proyectos sería:
`project_hide_archive_button`
Por último el Título en el manifest tiene que ser el mismo que el nombre del módulo:
En este caso sería : **'Partner Hide Archive Button'**

2022-05-09 14:41 UTC, JorgeQuinteros commented on hide_archive_button_by_group_for_contacts/__manifest__.py
> +    'name': 'Hide Archive Button By Groups For Contacts',
PD: Marca como Resuelto las conversaciones cuando tengas los cambios, thanks.

2022-05-09 15:17 UTC, Jeggrerd commented on hide_archive_button_by_group_for_contacts/__manifest__.py
> +    'name': 'Hide Archive Button By Groups For Contacts',
Vale, gracias Jorge :)

2022-05-13 06:57 UTC, JorgeQuinteros approved these changes
LGTM!

2022-05-13 06:57 UTC, merged