[ADD] group_validation
SDIsl/sdi-addons pull request #34
Opened 2020-10-05 11:23 UTC by ImanolRuiz

2020-10-05 15:05 UTC, JorgeQuinteros requested changes

2020-10-05 15:05 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +    'name': 'crm_lead_group_permits',
El nombre debe ser el mismo que el módulo, pero con Mayúsculas: CRM Lead Group Permits

2020-10-05 15:05 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +    'author': 'Imanol Ruiz, SDi Soluciones Informáticas',
Casí, nos lo han cambiado, ahora es: SDi Soluciones Digitales, cambialo en todos los sitios.

2020-10-05 15:05 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +    'category': 'Uncategorized',
Ponle una categoría que corresponda,busca algún modulo que modifique/Herede el CRM.

2020-10-05 15:05 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +        'base',
No es necesario que dependa de `base`.

2020-10-05 15:05 UTC, JorgeQuinteros commented on crm_lead_group_permits/security/ir.model.access.csv
> +crm.access_crm_lead,crm.lead,crm.model_crm_lead,sales_team.group_sale_salesman,1,0,0,0
Te falta una línea en blanco al final del fichero.

2020-10-06 08:07 UTC, oscars8a requested changes

2020-10-06 08:07 UTC, oscars8a commented on crm_lead_group_permits/__manifest__.py
> +#    SDi Soluciones Informáticas
Te falta aquí también el Soluciones Digitales

2020-10-06 08:07 UTC, oscars8a commented on crm_lead_group_permits/__manifest__.py
> +    'summary': 'Creation of a group that gives permits to create an opportunity',
Añade en el summario: only these group can do it, anybody else don't it.

Para remarcar que estamos quitando permisos al grupo de ventas "documentos propios".

2020-10-06 08:21 UTC, JorgeQuinteros requested changes

2020-10-06 08:21 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +    'name': 'CRM_LEAD_GROUP_PERMITS',
Con mayúsculas en cada palabra, pon lo que te dije en el primer comentario: `CRM Lead Group Permits`

2020-10-06 08:21 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +    'summary': 'Creation of a group that gives permits to create an opportunity. Only these group can do it, anybody else can\'t',
Esto no cumple con el PEP8, sobrepasa los 79 carácteres: https://www.python.org/dev/peps/pep-0008/

2020-10-06 08:29 UTC, oscars8a commented on crm_lead_group_permits/__manifest__.py
> +    'summary': 'Creation of a group that gives permits to create an opportunity. Only these group can do it, anybody else can\'t',
Además utilizamos la nomenclatura de la Flake8

2020-10-06 09:12 UTC, JorgeQuinteros requested changes

2020-10-06 09:12 UTC, JorgeQuinteros commented on crm_lead_group_permits/__manifest__.py
> +    'summary': 'Create a group with permits to edit opportunities. Only these group can edit',
Te sigues pasando, ahí tienes 96 caracteres. 
En visual Studio Code pulsa "F1", eliges "Select Linter" y selecciona Flake8, de esta manera te saldrá en rojo cuando te pases y en todos los sitios donde imcumplas las reglas de estilo de Python.
![image](https://user-images.githubusercontent.com/43784849/95182112-7d2cbb00-07c4-11eb-98bb-e6bd84ef5208.png)

2020-10-06 10:33 UTC, JorgeQuinteros commented on .vscode/settings.json
> +{
Este archivo no tienes que subirlo, se te ha colado.

2020-10-06 10:57 UTC, JorgeQuinteros approved these changes

2020-10-06 15:45 UTC, oscars8a requested changes

2020-10-06 15:45 UTC, oscars8a commented on crm_lead_group_permits/__manifest__.py
> +    'name': 'CRM_Lead_Group_Permits',
'name': 'CRM Lead Group Permits',

2020-10-06 15:49 UTC, oscars8a approved these changes
Bien hecho @ImanolRuiz !

2020-10-06 15:56 UTC, merged