12.0 sls
SDIsl/sdi-addons pull request #48
Opened 2021-03-12 08:23 UTC by Lopsanz

Adecuando la creación de remesas al modo "castellano"

2021-03-15 17:08 UTC, JorgeQuinteros approved these changes

2021-03-16 07:53 UTC, oscars8a requested changes
Sergio elimina el .pot que luego hay que actualizarlo a la vez que el .po o da problemas.

2021-03-16 07:53 UTC, oscars8a commented on payment_order_transactions_summary/i18n/payment_order_transactions_summary.pot
> +msgstr ""
@JorgeQuinteros el .pot yo no lo añadiría, que mantenerlo es un coñazo.

2021-03-16 08:28 UTC, oscars8a commented on payment_order_transactions_summary/i18n/payment_order_transactions_summary.pot
> +msgstr ""
@valentincastravete quita el fichero .pot gracias.

2021-03-16 09:57 UTC, JorgeQuinteros commented
@oscars8a Ya está el poedit quitado, procedo a mergear.

2021-03-16 09:57 UTC, merged

2021-03-16 10:18 UTC, oscars8a reviewed
Todo bien.