Vista Calendario en módulo Partes de horas
SDIsl/sdi-addons pull request #49
Opened 2021-03-17 14:30 UTC by valentincastravete

Módulo para agregar una vista calendario al módulo Partes de horas (hr_timesheet)

2021-05-05 08:35 UTC, oscars8a requested changes

2021-05-05 08:35 UTC, oscars8a commented on hr_timesheet_calendar/__manifest__.py
> +#    Copyright (C) 2020-Today SDi Soluciones Informáticas <www.sdi.es>
2021

2021-05-05 08:35 UTC, oscars8a commented on hr_timesheet_calendar/__manifest__.py
> +    'website': 'https://sdi.web.sdi.es/odoo/',
https://sdi.es/odoo

2021-05-05 08:35 UTC, oscars8a commented on hr_timesheet_calendar/views/hr_timesheet_views.xml
> +                <field name="unit_amount"/>
añadiría el proyecto y usuario

2021-05-05 10:12 UTC, valentincastravete commented on hr_timesheet_calendar/views/hr_timesheet_views.xml
> +                <field name="unit_amount"/>
El usuario no lo añadiría ya que esta vista es para "Mi parte de horas", no sirve para ver tareas de otras personas

2021-05-12 08:04 UTC, oscars8a approved these changes
:+1:

2021-05-12 08:28 UTC, JorgeQuinteros approved these changes

2021-05-12 08:28 UTC, merged