Editar y eliminar chat *sin límite de tiempo*
SDIsl/sdi-addons pull request #50
Opened 2021-03-18 12:44 UTC by valentincastravete

Módulo gratuito para editar y eliminar mensajes, mensajes internos y notas en el chatter de Odoo.

Lo he modificado para que no haya límite de tiempo para poder modificar esos mensajes.

Solo se pueden modificar y eliminar nuestros propios mensajes, a menos que seas un administrador, que podrás solo eliminar los de otros usuarios.

2021-05-05 09:00 UTC, oscars8a requested changes

2021-05-05 09:00 UTC, oscars8a commented on ks_chat_edit_and_delete/views/ks_assets.xml
> +</odoo>
añadir línea al final del documento.

2021-05-05 09:00 UTC, oscars8a commented on ks_chat_edit_and_delete/static/src/xml/ks_inherited_mail_config.xml
> +</templates>
añadir línea al final del documento

2021-05-05 09:00 UTC, oscars8a commented on ks_chat_edit_and_delete/static/src/js/ks_mail_extend.js
> +});
añadir línea al final del documento

2021-05-12 08:08 UTC, oscars8a approved these changes
👍🏻

2021-05-12 08:30 UTC, JorgeQuinteros approved these changes

2021-05-12 08:30 UTC, merged