[11.0] Code review flake8
SDIsl/sdi-addons pull request #54
Opened 2021-04-27 16:41 UTC by valentincastravete

2021-05-05 09:02 UTC, oscars8a requested changes

2021-05-05 09:02 UTC, oscars8a commented on activities_board/models/crm_lead.py
> +        compute='_compute_activities_count'
añadir , al final de la línea, hacer esto mismo dentro de todos los fields.Algo()

2021-05-12 08:11 UTC, oscars8a approved these changes
👍🏻

2021-05-24 14:11 UTC, JorgeQuinteros approved these changes
LGTM

2021-05-24 14:11 UTC, merged