Flake8 github action and pre-commit hook
SDIsl/sdi-addons pull request #55
Opened 2021-04-28 14:20 UTC by valentincastravete

2021-04-28 14:32 UTC, valentincastravete commented
Do not check it out yet, I will gonna fix the code.

2021-04-28 16:51 UTC, valentincastravete commented
You can check it out now and merge it if everything is ok.

2021-05-05 09:04 UTC, oscars8a requested changes

2021-05-05 09:04 UTC, oscars8a commented on activities_sync_event/__manifest__.py
>          'crm',
ordenar por orden alfabético, hacer lo mismo en todos los depends

2021-05-10 15:17 UTC, JorgeQuinteros approved these changes

2021-05-10 15:18 UTC, JorgeQuinteros commented
@oscars8a 
Por mi esto está Okey, apruebo, si da tu okey, lo probamos en odootest directamente para que todo esto vaya fluyendo.

2021-05-12 08:20 UTC, oscars8a requested changes

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/__manifest__.py
>      'summary': """
comillas simples

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/__manifest__.py
>      'description': """
comillas simples.

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/__manifest__.py
>      """,
comillas simples

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/__manifest__.py
> +        'activities_done'
Esto daría fallo, falta la coma al final de la línea.

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/models/__init__.py
>  from . import res_partner
al final de cada fichero una debe haber una línea en blanco

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/models/calendar_event.py
> +        :param domain: Search domain, see ``args`` parameter in ``search()``.
elimina todos los comentarios de métodos, usando clean no hace falta.

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/models/calendar_event.py
> +        Modification of the method so that it also eliminates the activity in
lo mismo, elimina comentarios

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/models/crm_lead.py
> +            ('editable', '=', False)], ['opportunity_id'], ['opportunity_id'])
añade una coma al final de la línea
dentro de [
    termina en , para que el git sea más limpio a futuro
]

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/models/crm_lead.py
> +        """ Open meeting's calendar view to schedule meeting on current
elimina comentarios

2021-05-12 08:20 UTC, oscars8a commented on activities_sync_event/models/crm_lead.py
> +            # action['context']['search_default_partner_ids'] = \
elimina código comentado

2021-05-12 10:36 UTC, oscars8a approved these changes

2021-05-12 10:56 UTC, merged