12.0 condiciones cliente
SDIsl/sdi-addons pull request #69
Opened 2021-05-27 08:01 UTC by Lopsanz

Módulo que amplía la creación de facturas desde la SO.
Cuando un pedido de venta no tiene condiciones de pago (plazo y modo), cogerlos del cliente.

2021-05-27 08:01 UTC, Lopsanz commented
Ping @oscars8a @JorgeQuinteros

2021-05-28 12:05 UTC, oscars8a requested changes
Esto esta maal

2021-05-28 12:05 UTC, oscars8a commented on product_tax_multicompany_management/__manifest__.py
> +    'name': 'Partner Name Address Autocomplete',
El nombre del módulo y la descripción no coinciden con el nombre de la carpeta

2021-05-28 12:07 UTC, Lopsanz commented on product_tax_multicompany_management/__manifest__.py
> +    'name': 'Partner Name Address Autocomplete',
Me perdí esa clase, sorry!

2021-05-28 12:08 UTC, oscars8a requested changes
creo que has mezclado 3 módulos

2021-05-28 12:08 UTC, oscars8a commented on product_tax_multicompany_management/views/product_view.xml
> +                <attribute name="widget">gplaces_autocomplete</attribute>
widget gplaces_autocomplete?????

2021-05-28 12:08 UTC, oscars8a commented on sale_order_partner_terms/__manifest__.py
> +    'name': 'Sale Order Invoice Partner',
esto esta maaal, no coincide el nombre con la carpeta y además el sumary es el mismo que el del módulo `sale_order_invoice_partner`

2021-05-28 12:08 UTC, oscars8a commented on sale_order_invoice_partner/__manifest__.py
> +    'author': 'Sergio Lop, SDi Soluciones Informáticas',
Creo que te has confundido de manifest ....

2021-05-31 09:58 UTC, oscars8a approved these changes
👍🏻

2021-05-31 10:00 UTC, merged